---
- hosts: all
  sudo: yes
  tasks:
    - name: install apt-transport-https
      apt:
        name: apt-transport-https
        state: present
        force: yes
        update_cache: yes
    - name: add dropbox repo key
      apt_key:
        keyserver: pgp.mit.edu
        id: 1C61A2656FB57B7E4DE0F4C1FC918B335044912E
    - name: add repo keys
      apt_key:
        url: "{{ item }}"
      with_items:
        - https://repo.skype.com/data/SKYPE-GPG-KEY
        - https://www.virtualbox.org/download/oracle_vbox_2016.asc
    - name: add apt repos
      apt_repository:
        repo: "{{ item }}"
        state: present
      with_items:
        - deb http://httpredir.debian.org/debian/ {{ ansible_lsb.codename }} main contrib non-free
        - deb [arch=i386,amd64] http://linux.dropbox.com/debian sid main
        - deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
        - deb http://dl.google.com/linux/musicmanager/deb/ stable main
        - deb http://dl.google.com/linux/talkplugin/deb/ stable main
        - deb http://download.virtualbox.org/virtualbox/debian {{ ansible_lsb.codename }} contrib non-free
        - deb [arch=amd64] https://repo.skype.com/deb stable main
      when: ansible_os_family == 'Debian'
    - name: install skype
      apt:
        name: skypeforlinux
      when: ansible_os_family == 'Debian'
    - name: install packages on Debian/Ubuntu
      apt:
        name: "{{ item }}"
        state: present
        force: yes
        update_cache: yes
      with_items:
        - acpi
        - acpica-tools
        - acpi-support
        - acpitool
        - silversearcher-ag
        - autoconf
        - autocutsel
        - automake
        - autotools-dev
        - bash-completion
        - bc
        - bison
        - blueman
        - bluetooth
        - bluez
        - bridge-utils
        - build-essential
        - busybox
        - bzip2
        - ca-certificates
        - clang
        - clusterssh
        - cmake
        - cmake
        - cpp
        - cpufrequtils
        - cscope
        - cups
        - curl
        - curl
        - daemontools
        - debootstrap
        - desktop-base
        - devscripts
        - direnv
        - dnsmasq
        - dput
        - dropbox
        - ebtables
        - ed
        - encfs
        - evince
        - exuberant-ctags
        - fakeroot
        - file
        - firmware-iwlwifi
        - flex
        - fontconfig
        - fontconfig-config
        - fonts-crosextra-caladea
        - fonts-crosextra-carlito
        - fonts-dejavu
        - fonts-dejavu-core
        - fonts-dejavu-extra
        - fonts-freefont-ttf
        - fonts-inconsolata
        - fonts-lato
        - fonts-liberation
        - fonts-linuxlibertine
        - fonts-lmodern
        - fonts-lyx
        - fonts-opensymbol
        - fonts-sil-gentium
        - fonts-sil-gentium-basic
        - fonts-texgyre
        - fonts-vlgothic
        - ftp
        - fuse
        - g++
        - gawk
        - gawk
        - gcc
        - gccgo
        - gcc-multilib
        - gdb
        - ghc
        - ghc-doc
        - ghostscript
        - gimp
        - git
        - git-man
        - git-svn
        - g++-multilib
        - gnome-keyring
        - gnupg
        - golang
        - golang-doc
        - grep
        - groff-base
        - gthumb
        - gzip
        - htop
        - iftop
        - imagemagick
        - info
        - iotop
        - iproute
        - iproute2
        - ipset
        - iptables
        - iptables-dev
        - iw
        - jq
        - laptop-detect
        - less
        - libreoffice
        - lightdm
        - lshw
        - lsof
        - m4
        - make
        - makedev
        - man-db
        - manpages
        - manpages-dev
        - mawk
        - mcelog
        - mplayer2
        - netcat
        - netcat-openbsd
        - network-manager
        - nfs-common
        - nfs-kernel-server
        - nmap
        - ntp
        - openssh-client
        - openssh-server
        - openssh-sftp-server
        - openssl
        - openvpn
        - p7zip-full
        - pandoc
        - parcellite
        - parted
        - passwd
        - pasystray
        - patch
        - patchutils
        - pavucontrol
        - pkg-config
        - pkg-mozilla-archive-keyring
        - pm-utils
        - pulseaudio
        - pulseaudio-module-bluetooth
        - pulseaudio-utils
        - puppet-lint
        - pwgen
        - python
        - python-all
        - python-all-dev
        - python-dev
        - python-dev
        - python-pip
        - qemu-kvm
        - qemu-system-common
        - qemu-system-x86
        - qemu-utils
        - rdesktop
        - redis-server
        - redis-tools
        - redshift
        - rfkill
        - rsync
        - sbuild
        - schroot
        - schroot-common
        - screen
        - screen
        - scrot
        - sed
        - socat
        - software-properties-common
        - sox
        - speedometer
        - sqlite3
        - sshfs
        - sshpass
        - ssl-cert
        - strace
        - sudo
        - sysstat
        - tar
        - tcpdump
        - tmux
        - traceroute
        - trayer
        - tree
        - ttf-bitstream-vera
        - ttf-dejavu
        - ttf-liberation
        - tzdata
        - ubuntu-archive-keyring
        - ubuntu-dev-tools
        - unzip
        - util-linux
        - valgrind
        - vim-gtk
        - virtualbox-5.1
        - virtualenv
        - virtualenvwrapper
        - vlc
        - vpnc-scripts
        - wget
        - wireshark
        - xclip
        - xdg-utils
        - xmobar
        - xmonad
        - xorg
        - xterm
        - xtightvncviewer
        - zip
        - zsh
      when: ansible_os_family == 'Debian'
    - name: download vagrant deb
      get_url:
        url: https://releases.hashicorp.com/vagrant/1.9.1/vagrant_1.9.1_x86_64.deb
        dest: /var/cache/apt/archives/vagrant_1.9.1_x86_64.deb
    - name: Install a .deb package from the internet.
      apt:
        deb: /var/cache/apt/archives/vagrant_1.9.1_x86_64.deb
