[General]
GeoLocale=system
SensitiveInfoMaskOn=true
ShowBiDirecSyncNoti=true
autoPlayGif=false
bForceMaximizeWM=false
captureHDCamera=true
cefInstanceCountLimit=-1
cefRefreshTime=0
chatListPanelLastWidth=320
com.disable.connection.pk.status=false
com.zoom.client.langid=0
conf.webserver=https://us05web.zoom.us
conf.webserver.vendor.default=https://zoom.us
currentMeetingId=88023134712
deviceID=50:E0:85:80:C8:3E
disableCef=false
disableUsePasskey=false
enable.host.auto.grab=true
enableAlphaBuffer=true
enableCefGpu=false
enableCefLog=false
enableCefOsrMode=true
enableCefTa=false
enableCloudSwitch=true
enableLog=true
enableMiniWindow=true
enableQmlCache=true
enableScreenSaveGuard=false
enableStartMeetingWithRoomSystem=false
enableTestMode=false
enableUnifywebviewTa=false
enableWaylandShare=false
enablegpucomputeutilization=false
fake.version=
flashChatTime=0
forceEnableTrayIcon=true
forceSSOURL=
hideCrashReport=false
host.auto.grab.interval=10
isTransCoding=false
legacyAvatarCacheCleaned=1774674783
logLevel=info
newMeetingWithVideo=true
noSandbox=false
playSoundForNewMessage=false
shareBarTopMargin=0
shortcut_as_global_ShortcutID_Screenshot=false
shortcut_as_global_ShortcutID_ShowHideFloatingMeetingControls=true
showOneTimePTAICTipHubble=false
showOneTimeQueriesOptionTip=true
showOneTimeSmartRecognitionCoackMark=true
showOneTimeTranslationUpSellTip=false
showSystemTitlebar=false
speaker_volume=255
sso_domain=.zoom.us
sso_gov_domain=.zoomgov.com
system.audio.type=default
systemDockMargin=0
timeFormat12HoursEnable=true
translationFreeTrialTipShowTime=0
upcoming_meeting_header_image=
useSystemTheme=false
userEmailAddress=v.nebehaj@gmail.com
webview.debug.enable=false
xwayland=true

[AS]
showframewindow=true

[CodeSnippet]
lastCodeType=0
wrapMode=0

[chat.recent]
recentlast.session=

[zoom_new_im]
is_landscape_mode=true
main_frame_pixel_pos_narrow="376,600"
main_frame_pixel_pos_wide="1012,960"
