# Hyprpaper wallpaper config.
# Replace this path later with a preferred wallpaper.

splash = false

wallpaper {
    monitor =
    path = /usr/share/backgrounds/gnome/adwaita-d.jpg
    fit_mode = cover
}
